### ISSUE TITLE
Replace spring-boot-parent with camunda-parent

### ISSUE THREAD

**Issue by hawky-4s-** [camunda/camunda-spring-boot-starter#2]
And just import the Spring-Boot parent pom in the dependencyManagement section.
This allows releasing the project to Camunda Nexus and Maven central.

**Comment by osteinhauer** [comment]
have to review some poms from other starter projects to keep conventions

**Comment by hawky-4s-** [comment]
I can do that.

**Comment by jangalinski** [comment]
Question is: which conventions do we want to keep? For a camunda community extension it would make more sense imho to follow the other extension projects (using camunda-release-parent).

**Comment by hawky-4s-** [comment]
It is no problem to use the camunda-release-parent as parent and just
import the spring-boot one as dependencyManagement. You just have to
configure the plugins, for example
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
</plugin>

by hand.

Cheers,
Christian

**Comment by jangalinski** [comment]
Exactly my point. LIke I did in my original set up: https://github.com/jangalinski/camunda-bpm-springboot/blob/master/pom.xml

**Comment by jangalinski** [comment]
Ups .. are you working on this? I started doing it and did not see the assignment .... I am pretty far, so I could just push soon ...

**Comment by hawky-4s-** [comment]
Hi Jan,

I am not working on it. Feel free to push it. I'll assign the issue to you.
