### ISSUE TITLE
apply code formatting rules

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-spring-boot-starter#6]
Add http://editorconfig.org/   taken from: https://github.com/camunda/camunda-bpm-webapp/tree/master/webapp and adjust to java. Also check https://github.com/camunda/camunda-bpm-platform/blob/master/settings/eclipse/formatter.xml

Basically: text-intent 2 spaces instead of tabs.

**Comment by hawky-4s-** [comment]
Would propose this setting.

```
# http://editorconfig.org
root = true
[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

**Comment by osteinhauer** [comment]
I would prefer to use the eclipse formatter because I am using the [Spring Tool Suite](https://spring.io/tools). But there should be no problem to have editorconfig and eclipse formatter if they provide the same rules?!

**Comment by osteinhauer** [comment]
seems the missing [line length(?)](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length) attribute breaks the camunda eclipse formatter rules. can you please set a length of 160? I don't like to edit the config because I cannot check the result.

**Comment by jangalinski** [comment]
will do .... 140 was a wild guess from my side, sorry! But it'll have to wait till tonight.
