### ISSUE TITLE
set up maven multi module project

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-spring-boot-starter#7]
I like that we keep the starters really small, focussed and stackable. 
But I'd prefer having a classic maven multi module set up like this:

/pom.xml - root pom for  project
/starter/pom.xml
/starter-cockpit/pom.xml
/examples/pom.xml - examples root
/examples/simple/pom.xml
/examples/web/pom.xml

That way the hierarchical structure of the modules reflects the folder structure, it is possible to build all modules with one build and  we do not have to define dependencies over and over again.

This is related to #2.

**Comment by hawky-4s-** [comment]
Agree. :+1:

**Comment by jangalinski** [comment]
I am already on it. Builds and tests ok, but I have some DB/dep issues when I manually start an application ... hopefully done this evening.
