### ISSUE TITLE
set up continuous integration

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-spring-boot-starter#9]
we should have automated builds and snapshot repos

**Comment by jangalinski** [comment]
Hi Christian, could you move forward with this? see #16 ... we are getting in trouble ... thanks!

**Comment by hawky-4s-** [comment]
Hi Jan,

I created the CI job and pinned it to JDK 6. You'll get emails if a build failure occurs.
Snapshot Upload to Camunda Nexus and Sonatype OSS Snapshot Repo is enabled.

Cheers,
Christian

**Comment by jangalinski** [comment]
nice! thanks
